apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbucket-depl
  labels:
    app: gitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitbucket
  template:
    metadata:
      labels:
        app: gitbucket
    spec:
      containers:
        - name: gitbucket
          image: rand1337/gitbucket-img:v3 
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/gitbucket"
            name: volume-for-bckt
          env:
          - name: GITBUCKET_DB_URL
            value: "jdbc:postgresql://$(POSTGRESQL_SERVICE_PORT_5432_TCP_ADDR):5432/gitbucket"   
          - name: GITBUCKET_DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: GITBUCKET_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
            #env:
            #- name: DB_URL
            #valueFrom:
            #configMapKeyRef:
            #name: postgres-config
            #key: db-url
            #command: ["export"]
            #args: ["DB_URL='jdbc:postgresql://$(POSTGRESQL_SERVICE_PORT_5432_TCP_ADDR):5432/gitbucket'"]
      volumes:
        - name: volume-for-bckt
          persistentVolumeClaim:
            claimName: bckt-claim 

---
apiVersion: v1
kind: Service
metadata:
  name: gitbucket-service
spec:
  type: LoadBalancer
  selector: 
    app: gitbucket
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080
      nodePort: 30140
