apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-for-psql
  labels:
    app: postgres-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: psql-nfs-service.default.svc.cluster.local
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: psql-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
