apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
  labels:
    app: postges-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      container:
      - name: postgresql
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresqldb
      volumes:
      - name: postgresqldb
        persistentVolumeClaim:
          claimName: psql-claim

---
# TO DO service

