apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-for-psql
  labels:
    app: postgres-db
spec:
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/psql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: postgres-db
