apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-for-bckt
  labels:
    app: gitbucket
spec:
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/bckt-volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bckt-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: gitbucket
